# Generated by Django 4.2.6 on 2023-11-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_address_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address line 2'),
        ),
    ]
