# Generated by Django 4.2.6 on 2023-11-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_alter_address_address1_alter_address_address2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_name',
        ),
    ]
