# Generated by Django 4.2.6 on 2023-11-12 22:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_alter_address_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('center_abbreviation', models.CharField(max_length=20, null=True)),
                ('district', models.CharField(choices=[('ALR', 'Anse La Raye'), ('CAN', 'Canaries'), ('CAS', 'Castries'), ('CHO', 'Choiseul'), ('DEN', 'Dennery'), ('GI', 'Gros Islet'), ('LAB', 'Laborie'), ('MIC', 'Micoud'), ('SOU', 'Soufirere'), ('VF', 'Vieux Fort')], max_length=150, null=True)),
                ('contact', models.CharField(max_length=150)),
                ('center_image', models.ImageField(upload_to='center_images')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150, null=True)),
                ('type_abbreviation', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today, null=True)),
                ('end_date', models.DateField(default=datetime.date.today, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('clinic_status', models.CharField(choices=[('urgent', 'Urgent Care'), ('phc', 'Primary Health Care'), ('other', 'Other')], max_length=125, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('clinic_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.clinictype')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.center')),
            ],
        ),
    ]
