# Generated by Django 4.2.6 on 2023-11-20 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_center_clinictype_clinicevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='google_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=500)),
                ('is_global', models.BooleanField(default=False, null=True)),
                ('article_image', models.ImageField(upload_to='article_images')),
                ('center_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.center')),
            ],
        ),
    ]
