# Generated by Django 4.2.6 on 2023-11-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_center_google_address_alter_center_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(null=True, upload_to='article_images'),
        ),
    ]
