# Generated by Django 4.2.6 on 2023-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0008_rename_google_address_center_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images'),
        ),
    ]
