# Generated by Django 4.2.6 on 2023-11-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0009_alter_article_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday'), (8, 'Holidays')], unique=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.center')),
            ],
        ),
        migrations.AddConstraint(
            model_name='openinghours',
            constraint=models.UniqueConstraint(fields=('center', 'weekday'), name='center operating days'),
        ),
    ]
