# Generated by Django 4.2.6 on 2023-11-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0014_alter_clinicevent_clinic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
