# Generated by Django 4.2.6 on 2023-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0016_alter_customuser_is_active_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
