# Generated by Django 4.2.6 on 2023-12-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0018_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='update_status',
            field=models.BooleanField(default=False),
        ),
    ]
