# Generated by Django 4.2.6 on 2023-12-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0020_alter_address_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='display_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
