# Generated by Django 4.2.6 on 2023-12-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0024_center_tags_alter_article_center_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=10000),
        ),
    ]
