# Generated by Django 4.2.6 on 2023-12-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0028_article_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec massa enim, ultrices ac quam in, semper aliquam sem. Sed ante ex, interdum lacinia urna at, faucibus hendrerit enim. Morbi varius porta neque, quis viverra ex posuere sit amet. Nam quis arcu eget dui vestibulum mollis', max_length=200, null=True),
        ),
    ]
