# Generated by Django 4.2.6 on 2023-12-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0029_alter_article_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name': 'Opening Hours', 'verbose_name_plural': 'Opening Hours'},
        ),
        migrations.AddField(
            model_name='openinghours',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
