# Generated by Django 4.2.6 on 2023-12-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0030_alter_openinghours_options_openinghours_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='annoucement.png', null=True, upload_to='article_images'),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_image',
            field=models.ImageField(default='medical_center_default.jpg', upload_to='center_images'),
        ),
    ]
