# Generated by Django 4.2.6 on 2024-01-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0032_center_center_description_alter_article_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicevent',
            name='clinic_status',
        ),
    ]
