# Generated by Django 4.2.6 on 2024-01-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0033_remove_clinicevent_clinic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicevent',
            name='is_expired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
