# Generated by Django 4.2.6 on 2024-01-09 15:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('healthapp', '0035_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, default='This is a placeholder subtitle', max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=10000)),
                ('is_global', models.BooleanField(default=False, null=True)),
                ('article_image', models.ImageField(blank=True, default='annoucement.png', null=True, upload_to='article_images')),
                ('centers', models.ManyToManyField(blank=True, to='healthapp.center')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
