# Generated by Django 4.2.6 on 2024-01-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0038_center_local_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'Holidays')], unique=True)),
                ('is_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
                ('center', models.ManyToManyField(blank=True, to='healthapp.center')),
            ],
            options={
                'verbose_name': 'Opening Time',
                'verbose_name_plural': 'Opening Times',
            },
        ),
    ]
