# Generated by Django 4.2.6 on 2024-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0042_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
