# Generated by Django 4.2.6 on 2024-02-26 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0044_alter_newsarticle_centers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicevent',
            name='clinic_type',
        ),
        migrations.AlterField(
            model_name='clinicevent',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.center'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='centers',
            field=models.ManyToManyField(blank=True, to='healthapp.center'),
        ),
        migrations.DeleteModel(
            name='ClinicType',
        ),
    ]
